### ISSUE TITLE
tgphotos not on docker hub

### ISSUE THREAD

**Issue by ehte92** [Radiquum/TG-Photos#3]
Pulling tgphotos (tgphotos:latest)...
ERROR: pull access denied for tgphotos, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

I wsa unable to find tgphotos on docker hub

**Comment by Radiquum** [comment]
It's not available in the dockerhub, since I didn't publish it there.

If you followed setup instructions in the readme, then image is called just tgphotos, just remove the :latest tag in docker-compose file, or rebuild the image with tgphotos:latest name instead of just tgphotos.

thank you for spotting my mistake
